title: Inertiae
email: jp_bruyere@hotmail.com
description: >-
  My developpement blog.

#baseurl: "vkvg" # the subpath of your site, e.g. /blog
url: "https://jpbruyere.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jpbruyere
github_username: jpbruyere

# Build settings
#remote_theme: riggraz/no-style-please
theme: no-style-please
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

plugins:
  - jekyll-feed
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
